volumes:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${WEB_PORT:-20080}:8000
    volumes:
      - ..:/workspace
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASS:-secret}
  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-13306}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - "TZ=Asia/Tokyo"
