name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  php-lint-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: nanasess/setup-php@master
        with:
          php-version: 8.2
      - name: cache vendor
        id: cache
        uses: actions/cache@v4
        with:
          path: ./src/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
      - name: copy .env
        run: cp .env.example .env
      - name: generate key
        run: php artisan key:generate
      - name: Create Database
        run: touch database/database.sqlite
      - name: migrate
        run: php artisan migrate
      - run: composer run lint
      - run: php artisan test
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
