name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: nanasess/setup-php@master
        with:
          php-version: 8
      - run: php -v
      - run: composer install
        working-directory: ./src
      - run: composer run lint
        working-directory: ./src
      - run: php artisan test
